### ISSUE TITLE
Milestone 0.03

### ISSUE THREAD

**Issue by GuillaumeFavelier** [GuillaumeFavelier/blockbuilder#2]
Among the goals of the [roadmap](#1), the following will be available for the next milestone:

- [x] Refactor area selection (experimental code)
- [x] Allow the app to hold it's own event loop
- [x] Add an option to toggle the block edges visibility
- [x] Fix OpenGL context creation issue (at `Initialize()`) 
- [x] Disable default VTK interaction 
- [x] Fix bug with coincident topology between grid and blocks
- [x] Add key bindings to rcParams (at least for camera bindings)
- [x] Refactor graphics completely and rename into plotter
- [x] Remove dependency to pyvista
- [x] Add an area selection toggle
- [x] Add docstrings and make `pydocstyle` happy
- [x] Add directory changes and use one changelog for each release
